package com.globant.invoices.app.common;

import com.globant.invoices.model.AInvoicesImpl;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 28 17:19:51 CST 2014
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    AInvoicesImpl findaInvoicesImplById(int aInvoicesImplId);

    AInvoicesImpl updateInvoicesImplById(int aInvoicesImplId,
                                         int aInvoicesImplIdJdedwars);
}
