package com.globant.invoices.app;

import com.globant.invoices.app.common.AppModule;
import com.globant.invoices.model.AInvoicesImpl;

import oracle.jbo.Key;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 28 17:01:58 CST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for AInvoicesView1.
     * @return AInvoicesView1
     */
    public ViewObjectImpl getAInvoicesView1() {
        return (ViewObjectImpl)findViewObject("AInvoicesView1");
    }

    /**
     * Container's getter for EmployeesView1.
     * @return EmployeesView1
     */
    public ViewObjectImpl getEmployeesView1() {
        return (ViewObjectImpl)findViewObject("EmployeesView1");
    }

    /**
     * Container's getter for AInvoicesView2.
     * @return AInvoicesView2
     */
    public ViewObjectImpl getAInvoicesView2() {
        return (ViewObjectImpl)findViewObject("AInvoicesView2");
    }

    /**
     * Container's getter for AInvoicesEmployeesFk1Link1.
     * @return AInvoicesEmployeesFk1Link1
     */
    public ViewLinkImpl getAInvoicesEmployeesFk1Link1() {
        return (ViewLinkImpl)findViewLink("AInvoicesEmployeesFk1Link1");
    }
    
    /**
     * Find an invoice by id
     * 
     * @param aInvoicesImplId
     * @return
     */
    public AInvoicesImpl findaInvoicesImplById(int aInvoicesImplId) {
        
        System.out.println(String.format("Serving: findaInvoicesImplById: %d.", aInvoicesImplId ));
        
        EntityDefImpl aInvoicesDef = AInvoicesImpl.getDefinitionObject();
        Key orderKey = AInvoicesImpl.createPrimaryKey(new DBSequence(aInvoicesImplId));
        
        EntityImpl result = (EntityImpl) aInvoicesDef.findByPrimaryKey(getDBTransaction(),orderKey);                
        
        System.out.println(String.format("Endind: findaInvoicesImplById: %s.", ((AInvoicesImpl) result).getIdJdedwars());
        
        return (AInvoicesImpl) result;
    }
    
    /**
     * Update IDJEdwards to an AInvoicesImpl.
     * 
     * @param aInvoicesImplId
     * @param aInvoicesImplIdJdedwars
     * @return
     */
    public AInvoicesImpl updateInvoicesImplById(int aInvoicesImplId, int aInvoicesImplIdJdedwars) {
        
        System.out.println(String.format("Serving updateInvoicesImplById: %d %d", aInvoicesImplId, aInvoicesImplIdJdedwars));
        
        AInvoicesImpl aInvoicesImpl = this.findaInvoicesImplById(aInvoicesImplId);
                        
        
        oracle.jbo.domain.Number invoiceIdJdedwars = new oracle.jbo.domain.Number(aInvoicesImplIdJdedwars);
        aInvoicesImpl.setIdJdedwars(invoiceIdJdedwars);    
        
        // This is not working !
        getDBTransaction().commit();
        
        System.out.println(String.format("Ending updateInvoicesImplById: %s.", aInvoicesImpl ));            
        
        return aInvoicesImpl;
    }
}
