package com.globant.invoices.webservices.proxy;

import java.util.concurrent.Future;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(wsdlLocation="http://localhost:7101/Invoices_v1-JDEdwards_v1-context-root/InvoicesServerSoap12HttpPort?WSDL",
  targetNamespace="http://invoices.globant.com/", name="InvoicesServer")
@XmlSeeAlso(
  { com.globant.invoices.webservices.proxy.ObjectFactory.class })
public interface InvoicesServer
{
  @WebMethod
  @Action(input="http://invoices.globant.com/InvoicesServer/getInvoiceServerIDRequest",
    output="http://invoices.globant.com/InvoicesServer/getInvoiceServerIDResponse")
  @ResponseWrapper(localName="getInvoiceServerIDResponse",
    targetNamespace="http://invoices.globant.com/", className="com.globant.invoices.webservices.proxy.GetInvoiceServerIDResponse")
  @RequestWrapper(localName="getInvoiceServerID", targetNamespace="http://invoices.globant.com/",
    className="com.globant.invoices.webservices.proxy.GetInvoiceServerID")
  @WebResult(targetNamespace="")
  public int getInvoiceServerID(@WebParam(targetNamespace="", name="arg0")
    int arg0);

  @WebMethod(operationName="getInvoiceServerID")
  @Action(input="http://invoices.globant.com/InvoicesServer/getInvoiceServerIDRequest",
    output="http://invoices.globant.com/InvoicesServer/getInvoiceServerIDResponse")
  @RequestWrapper(localName="getInvoiceServerID", targetNamespace="http://invoices.globant.com/",
    className="com.globant.invoices.webservices.proxy.GetInvoiceServerID")
  @ResponseWrapper(localName="getInvoiceServerIDResponse",
    targetNamespace="http://invoices.globant.com/", className="com.globant.invoices.webservices.proxy.GetInvoiceServerIDResponse")
  @WebResult(targetNamespace="")
  public Response<com.globant.invoices.webservices.proxy.GetInvoiceServerIDResponse> getInvoiceServerIDAsync(@WebParam(targetNamespace="",
      name="arg0")
    int arg0);

  @WebMethod(operationName="getInvoiceServerID")
  @Action(input="http://invoices.globant.com/InvoicesServer/getInvoiceServerIDRequest",
    output="http://invoices.globant.com/InvoicesServer/getInvoiceServerIDResponse")
  @RequestWrapper(localName="getInvoiceServerID", targetNamespace="http://invoices.globant.com/",
    className="com.globant.invoices.webservices.proxy.GetInvoiceServerID")
  @ResponseWrapper(localName="getInvoiceServerIDResponse",
    targetNamespace="http://invoices.globant.com/", className="com.globant.invoices.webservices.proxy.GetInvoiceServerIDResponse")
  @WebResult(targetNamespace="")
  public Future<?> getInvoiceServerIDAsync(@WebParam(targetNamespace="",
      name="arg0")
    int arg0, AsyncHandler<com.globant.invoices.webservices.proxy.GetInvoiceServerIDResponse> asyncHandler);

  @WebMethod(operationName="getInvoiceServerID_v2")
  @Action(input="http://invoices.globant.com/InvoicesServer/getInvoiceServerID_v2Request",
    output="http://invoices.globant.com/InvoicesServer/getInvoiceServerID_v2Response")
  @ResponseWrapper(localName="getInvoiceServerID_v2Response",
    targetNamespace="http://invoices.globant.com/", className="com.globant.invoices.webservices.proxy.GetInvoiceServerIDV2Response")
  @RequestWrapper(localName="getInvoiceServerID_v2", targetNamespace="http://invoices.globant.com/",
    className="com.globant.invoices.webservices.proxy.GetInvoiceServerIDV2")
  @WebResult(targetNamespace="")
  public String getInvoiceServerIDV2(@WebParam(targetNamespace="", name="arg0")
    int arg0, @WebParam(targetNamespace="", name="arg1")
    String arg1);

  @WebMethod(operationName="getInvoiceServerID_v2")
  @Action(input="http://invoices.globant.com/InvoicesServer/getInvoiceServerID_v2Request",
    output="http://invoices.globant.com/InvoicesServer/getInvoiceServerID_v2Response")
  @ResponseWrapper(localName="getInvoiceServerID_v2Response",
    targetNamespace="http://invoices.globant.com/", className="com.globant.invoices.webservices.proxy.GetInvoiceServerIDV2Response")
  @RequestWrapper(localName="getInvoiceServerID_v2", targetNamespace="http://invoices.globant.com/",
    className="com.globant.invoices.webservices.proxy.GetInvoiceServerIDV2")
  @WebResult(targetNamespace="")
  public Response<com.globant.invoices.webservices.proxy.GetInvoiceServerIDV2Response> getInvoiceServerIDV2Async(@WebParam(targetNamespace="",
      name="arg0")
    int arg0, @WebParam(targetNamespace="", name="arg1")
    String arg1);

  @WebMethod(operationName="getInvoiceServerID_v2")
  @Action(input="http://invoices.globant.com/InvoicesServer/getInvoiceServerID_v2Request",
    output="http://invoices.globant.com/InvoicesServer/getInvoiceServerID_v2Response")
  @ResponseWrapper(localName="getInvoiceServerID_v2Response",
    targetNamespace="http://invoices.globant.com/", className="com.globant.invoices.webservices.proxy.GetInvoiceServerIDV2Response")
  @RequestWrapper(localName="getInvoiceServerID_v2", targetNamespace="http://invoices.globant.com/",
    className="com.globant.invoices.webservices.proxy.GetInvoiceServerIDV2")
  @WebResult(targetNamespace="")
  public Future<?> getInvoiceServerIDV2Async(@WebParam(targetNamespace="",
      name="arg0")
    int arg0, @WebParam(targetNamespace="", name="arg1")
    String arg1, AsyncHandler<com.globant.invoices.webservices.proxy.GetInvoiceServerIDV2Response> asyncHandler);

  @WebMethod(operationName="getInvoiceServerID_v3")
  @Action(input="http://invoices.globant.com/InvoicesServer/getInvoiceServerID_v3Request",
    output="http://invoices.globant.com/InvoicesServer/getInvoiceServerID_v3Response")
  @ResponseWrapper(localName="getInvoiceServerID_v3Response",
    targetNamespace="http://invoices.globant.com/", className="com.globant.invoices.webservices.proxy.GetInvoiceServerIDV3Response")
  @RequestWrapper(localName="getInvoiceServerID_v3", targetNamespace="http://invoices.globant.com/",
    className="com.globant.invoices.webservices.proxy.GetInvoiceServerIDV3")
  @WebResult(targetNamespace="")
  public com.globant.invoices.webservices.proxy.Invoice getInvoiceServerIDV3(@WebParam(targetNamespace="",
      name="arg0")
    com.globant.invoices.webservices.proxy.Invoice arg0);

  @WebMethod(operationName="getInvoiceServerID_v3")
  @Action(input="http://invoices.globant.com/InvoicesServer/getInvoiceServerID_v3Request",
    output="http://invoices.globant.com/InvoicesServer/getInvoiceServerID_v3Response")
  @ResponseWrapper(localName="getInvoiceServerID_v3Response",
    targetNamespace="http://invoices.globant.com/", className="com.globant.invoices.webservices.proxy.GetInvoiceServerIDV3Response")
  @RequestWrapper(localName="getInvoiceServerID_v3", targetNamespace="http://invoices.globant.com/",
    className="com.globant.invoices.webservices.proxy.GetInvoiceServerIDV3")
  @WebResult(targetNamespace="")
  public Response<com.globant.invoices.webservices.proxy.GetInvoiceServerIDV3Response> getInvoiceServerIDV3Async(@WebParam(targetNamespace="",
      name="arg0")
    com.globant.invoices.webservices.proxy.Invoice arg0);

  @WebMethod(operationName="getInvoiceServerID_v3")
  @Action(input="http://invoices.globant.com/InvoicesServer/getInvoiceServerID_v3Request",
    output="http://invoices.globant.com/InvoicesServer/getInvoiceServerID_v3Response")
  @ResponseWrapper(localName="getInvoiceServerID_v3Response",
    targetNamespace="http://invoices.globant.com/", className="com.globant.invoices.webservices.proxy.GetInvoiceServerIDV3Response")
  @RequestWrapper(localName="getInvoiceServerID_v3", targetNamespace="http://invoices.globant.com/",
    className="com.globant.invoices.webservices.proxy.GetInvoiceServerIDV3")
  @WebResult(targetNamespace="")
  public Future<?> getInvoiceServerIDV3Async(@WebParam(targetNamespace="",
      name="arg0")
    com.globant.invoices.webservices.proxy.Invoice arg0, AsyncHandler<com.globant.invoices.webservices.proxy.GetInvoiceServerIDV3Response> asyncHandler);

  @WebMethod(operationName="getInvoiceServerID_v4")
  @Action(input="http://invoices.globant.com/InvoicesServer/getInvoiceServerID_v4Request",
    output="http://invoices.globant.com/InvoicesServer/getInvoiceServerID_v4Response")
  @ResponseWrapper(localName="getInvoiceServerID_v4Response",
    targetNamespace="http://invoices.globant.com/", className="com.globant.invoices.webservices.proxy.GetInvoiceServerIDV4Response")
  @RequestWrapper(localName="getInvoiceServerID_v4", targetNamespace="http://invoices.globant.com/",
    className="com.globant.invoices.webservices.proxy.GetInvoiceServerIDV4")
  @WebResult(targetNamespace="")
  public com.globant.invoices.webservices.proxy.InvoiceResult getInvoiceServerIDV4(@WebParam(targetNamespace="",
      name="arg0")
    com.globant.invoices.webservices.proxy.InvoiceRequest arg0);

  @WebMethod(operationName="getInvoiceServerID_v4")
  @Action(input="http://invoices.globant.com/InvoicesServer/getInvoiceServerID_v4Request",
    output="http://invoices.globant.com/InvoicesServer/getInvoiceServerID_v4Response")
  @ResponseWrapper(localName="getInvoiceServerID_v4Response",
    targetNamespace="http://invoices.globant.com/", className="com.globant.invoices.webservices.proxy.GetInvoiceServerIDV4Response")
  @RequestWrapper(localName="getInvoiceServerID_v4", targetNamespace="http://invoices.globant.com/",
    className="com.globant.invoices.webservices.proxy.GetInvoiceServerIDV4")
  @WebResult(targetNamespace="")
  public Response<com.globant.invoices.webservices.proxy.GetInvoiceServerIDV4Response> getInvoiceServerIDV4Async(@WebParam(targetNamespace="",
      name="arg0")
    com.globant.invoices.webservices.proxy.InvoiceRequest arg0);

  @WebMethod(operationName="getInvoiceServerID_v4")
  @Action(input="http://invoices.globant.com/InvoicesServer/getInvoiceServerID_v4Request",
    output="http://invoices.globant.com/InvoicesServer/getInvoiceServerID_v4Response")
  @ResponseWrapper(localName="getInvoiceServerID_v4Response",
    targetNamespace="http://invoices.globant.com/", className="com.globant.invoices.webservices.proxy.GetInvoiceServerIDV4Response")
  @RequestWrapper(localName="getInvoiceServerID_v4", targetNamespace="http://invoices.globant.com/",
    className="com.globant.invoices.webservices.proxy.GetInvoiceServerIDV4")
  @WebResult(targetNamespace="")
  public Future<?> getInvoiceServerIDV4Async(@WebParam(targetNamespace="",
      name="arg0")
    com.globant.invoices.webservices.proxy.InvoiceRequest arg0, AsyncHandler<com.globant.invoices.webservices.proxy.GetInvoiceServerIDV4Response> asyncHandler);
}
