package com.globant.invoices.webservices.proxy;

import javax.xml.ws.WebServiceRef;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

public class InvoicesServerSoap12HttpPortClient
{
  @WebServiceRef
  private static InvoicesServerService invoicesServerService;

  public static void main(String [] args)
  {
    invoicesServerService = new InvoicesServerService();
    InvoicesServer invoicesServer = invoicesServerService.getInvoicesServerSoap12HttpPort();
    // Add your code to call the desired methods.
  }
}
