package com.globant.twitter.model.common;

import java.util.List;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 11 16:27:53 CST 2014
// ---------------------------------------------------------------------
public interface VO_Mentions extends ViewObject {
    void testMethod_v1();

    String testMethod_v2(String values);

}
